/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/w068k5oOTbn
 */
import { Button } from "@/components/ui/button"
import { CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import axios from "axios"
import { BACKEND_URL } from "../../config"
import { useState } from "react"
import { useNavigate } from "react-router-dom"

export function Publish() {
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const navigate = useNavigate();
  return (
    <Card className="w-full max-w-4xl mx-auto rounded-lg border-none">
      <CardHeader className="flex flex-col items-start gap-1 p-6 ">
        <h2 className="text-3xl font-bold tracking-wide">Create a new post</h2>
        <p className="text-m font-normal text-gray-500">Start writing your blog post</p>
      </CardHeader>
      <CardContent className="p-6">
        <div className="grid gap-4">
          <label className="flex flex-col space-y-1 text-2xl font-medium" htmlFor="title">
            Title
            <Input onChange={(e) => {
              setTitle(e.target.value);
            }} className="mt-1 text-2xl " id="title" placeholder="Enter the title of the post" />
          </label>
          <label className="flex flex-col space-y-1 text-2xl font-medium" htmlFor="body">
            Body
            <Textarea onChange={(e) => {
              setDescription(e.target.value);
            }}className="min-h-[200px] mt-1 text-base" id="body" placeholder="Enter the body of the post" />
          </label>
        </div>
      </CardContent>
      <CardFooter className="flex p-6 gap-2 border-t">
        <Button onClick={async ()=>{const response =await axios.post(`${BACKEND_URL}/api/v1/blog`,{
          title,
          content:description,
          published:true
        },{
          headers:{
            Authorization: localStorage.getItem("token")
          }
        });
        navigate(`/blog/${response.data.postId}`)
        }} className="ml-2 rounded-full border-pink-400 border-pink-400 text-pink-400" variant="outline">
          Publish
        </Button>
      </CardFooter>
    </Card>
  )
}




